### ISSUE TITLE
Exception during summary printout

### ISSUE THREAD

**Issue by simon987** [pirate/ArchiveBox#188] opened 2019-03-22 00:07 UTC
### Describe the bug
Exception during summary printout

### Steps to reproduce
1. `echo 'https://exemple.com/' | ./archive`

### Screenshots or log output
```
Traceback (most recent call last):
  File "./archive", line 132, in <module>
    main(*sys.argv)
  File "./archive", line 93, in main
    update_archive_data(import_path=import_path, resume=resume)
  File "./archive", line 124, in update_archive_data
    log_archiving_finished(len(links))
  File "/mnt/Data3/WebArchive/ArchiveBox/archivebox/logs.py", line 158, in log_archiving_finished
    seconds = end_ts - _LAST_RUN_STATS['start_ts'].timestamp()
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'float'
```

### Software versions
(please complete the following information)

 - OS: `4.19.28-1-MANJARO #1 SMP PREEMPT Sun Mar 10 08:32:42 UTC 2019 x86_64 GNU/Linux`
 - ArchiveBox version: `d7981170810cfcaf12978226c00e3e95568a4659`
 - Docker version: n/a
 - Python version: 3.7.2
 - Chrome version: n/a
 - Wget version: n/a

**Comment by pirate** [comment] 2019-03-22 01:24
Duplicate of https://github.com/pirate/ArchiveBox/issues/185

**Closed** 2019-03-22 01:25 UTC
