### ISSUE TITLE
Add urls field for admin and/or everybody

### ISSUE THREAD

**Issue by Solemnly** [pirate/ArchiveBox#293] opened 2019-11-07 13:16 UTC
I think that would be a cool feature.

## Type 

 - [x] General question or discussion
 - [ ] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute money to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment] 2019-11-07 20:12
> Add urls field for admin and/or everybody

Not sure what your suggestion is for exactly... can you elaborate a bit?

**Comment by dataarchivist** [comment] 2019-11-19 17:39
Same here. We (I hope I understand him right) mean we wish to have a simple website too, like archive.org where user can submit an url who should be saved then.

**Comment by pirate** [comment] 2019-11-20 17:59
Ah, then this is a duplicate of https://github.com/pirate/ArchiveBox/issues/221

**Closed by pirate** 2019-11-20 17:59 UTC
Labels: changes: behavior, status: idea phase
