### ISSUE TITLE
Auto OK Cookie dialogue

### ISSUE THREAD

**Issue by maxmopp** [pirate/ArchiveBox#172] opened 2019-03-11 12:43 UTC
Is there any way to have a auto OK for  Cookie dialogues eg:
https://mobil.derstandard.at/2000084118441/Drohnen-fliegen-im-Ausland-Was-man-darf-und-was-man
This site will not be archived at all otherwise
I did not get, where to add the --load-cookies cookies.txt as in #150

and maybe the inclusion of an anti adblock greasmonkey script, eg https://greasyfork.org/de/scripts/34815-anti-adblock-killer-reek- same site lets you download 3 pages only therwise

**Comment by pirate** [comment] 2019-03-11 19:26
Duplicate of: https://github.com/pirate/ArchiveBox/issues/51

You can specify a cookies file to use using the [`COOKIES_FILE`](https://github.com/pirate/ArchiveBox/wiki/Configuration#cookies_file) env option.

**Closed by pirate** 2019-03-11 19:26 UTC
