### ISSUE TITLE
Bugfix: youtube-dl HTTPError 405: 'Method Not Allowed'

### ISSUE THREAD

**Issue by dataarchivist** [pirate/ArchiveBox#301] opened 2019-11-20 14:13 UTC
I start running in more and more:

> youtube-dl HTTPError 405: 'Method Not Allowed'

errors. Due the fact that ubuntu still have a version of 2018, I wish to use the latest.
youtube-dl -U didnt work for updateing, so, use:

> sudo wget https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl
> sudo chmod a+x /usr/local/bin/youtube-dl
> hash -r

So a youtube-dl --version says now:
2019.11.05

But this returns in

> Traceback (most recent call last):
  File "./archive", line 136, in <module>
    main(*sys.argv)
  File "./archive", line 98, in main
    update_archive_data(import_path=import_path, resume=resume)
  File "./archive", line 106, in update_archive_data
    all_links, new_links = load_links_index(out_dir=OUTPUT_DIR, import_path=impo                       rt_path)
  File "/home/rusty/ArchiveBox/archivebox/index.py", line 61, in load_links_inde                       x
    existing_links = parse_json_links_index(out_dir)
  File "/home/rusty/ArchiveBox/archivebox/index.py", line 108, in parse_json_lin                       ks_index
    links = json.load(f)['links']
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 95679 column 22 (cha                       r 4551363)

No matter if with echo or just ./archive.
I will investigate it a little bit more, may I found a solution before @pirate found it. ;)

EDIT: Dunno what the problem was, I delete AB and make a fresh install, copy my config.py and everything runs well again Oo...!

**Comment by pirate** [comment] 2019-11-20 17:55
This is unrelated to youtube-dl, it's caused by the archive JSON index getting corrupted due to cancelling mid-run, this issue is already fixed in the next version.

**Closed by pirate** 2019-11-20 17:55 UTC
Labels: changes: bugfixes
